swagger: "2.0"
info:
  description: NodeJS Mentoring API
  version: 1.0.0
  title: NodeJS Mentoring
  contact:
    email: anton.slem@hmail.com
host: localhost:10010
basePath: /api
tags:
  - name: city
    description: CRUD operations for city
schemes:
  - http
paths:
  /cities:
    x-swagger-router-controller: citiesController
    get:
      operationId: getAll
      tags:
        - city
      summary: Find all cities
      description: Returns all cities
      produces:
        - application/json
      responses:
        200:
          description: A list of Cities
          schema:
            $ref: '#/definitions/Cities' 
        400:
          description: System error
    post:
      operationId: create
      tags:
        - city
      summary: Create a new city
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      - in: body
        name: body
        description: City object that needs to be created
        required: true
        schema:
          $ref: '#/definitions/City'
      responses:
        201:
          description: City succesfully created
          schema:
            $ref: '#/definitions/City' 
        400:
          description: Invalid input
  /cities/{cityId}:
    x-swagger-router-controller: citiesController
    put:
      operationId: update
      tags:
        - city
      summary: Update the city
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: cityId
          in: path
          required: true
          description: ID of the city
          type: string
        - name: body
          in: body
          description: City object that needs to be updated
          required: true
          schema:
            $ref: '#/definitions/City'
      responses:
        200:
          description: City succesfully updated
          schema:
            $ref: '#/definitions/City' 
        400:
          description: Invalid input
    delete:
      operationId: remove
      tags:
        - city
      summary: Remove the city
      parameters:
        - name: cityId
          in: path
          required: true
          description: ID of the city
          type: string
      responses:
        204:
          description: City succesfully removed
        400:
          description: Invalid input
definitions:
  City:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      country:
        type: string
  Cities:
    type: array
    items:
      $ref: '#/definitions/City'
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
